service: asset-management-api
provider:
  name: aws
  runtime: nodejs16.16.0
  stage: main
  region: ca-central-1
  memorySize: 128
functions:
  app:
    handler: src/index.ts
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
